name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [flake8 --all-files,black --all-files, check-added-large-files --all-files,mypy --all-files, nbstripout --all-files, pyupgrade --all-files]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: ${{ matrix.version }}

# --hook-stage manual --all-files
